name: DesktopCI

on: [workflow_dispatch, push, pull_request]

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust Stable
        run: rustup update stable && rustup default stable

      - name: Build Crater
        run: cargo build

      - name: Run Crater tests
        run: |
          cd Desktop && cargo test -- --test-threads=1
